<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>手写promise</title>
</head>

<body>

    <script>

        //手写promise思路
        //1. 第一步有三种状态, pending,fulfilled,rejected
        //2. 定时成功的链式回调
        //3. 定义失败的链式回调
        //4. 定义函数的then方法.用来访问最终的结果
        //4.1 then()第一个参数是成功回调函数,如果不是函数应该被忽略
        // 4.2 then()第二个参数应该是一个失败的回调函数,如果不是函数应该被忽略




        //4. 定义返回的结果

        // class MyPromise {
        //     constructor(fn) {
        //         this.status = 'pending';//定义状态
        //         this.result = null; // 定义返回结果
        //         this.onResolvedCallbacks = [];
        //         this.onRejectedCallbacks = [];

        //         // 成功函数
        //         const resolve = (value) => {
        //             if (this.status === 'pending') {
        //                 this.status = 'fulfilled';//定义状态  
        //                 this.result = value; // 定义返回结果
        //                 this.onResolvedCallbacks.forEach((callback) => {
        //                     callback(value)
        //                 })
        //             }
        //         }

        //         //失败函数
        //         const reject = (reason) => {
        //             if (this.status === 'pending') {
        //                 this.status = 'rejected';//定义状态  
        //                 this.result = reason; // 定义返回结果
        //                 this.onRejectedCallbacks.forEach((callback) => {
        //                     callback(reason)
        //                 })
        //             }
        //         }


        //         try {
        //             fn(resolve, reject)
        //         } catch (error) {
        //             reject(error)
        //         }
        //     }

        //     then(onfulfilled, onrejected) {
        //         //判断onfulfilled和onrejected是不是函数,如果不是转换成返回当前值的函数,如果是就直接赋值;
        //         onfulfilled = typeof onfulfilled === 'function' ? onfulfilled : (value) => value;

        //         onrejected = typeof onrejected === 'function' ? onrejected : (reason) => {
        //             throw reason
        //         };


        //         // 整体的返回值是一个新的promise,用于then式调用

        //         return new MyPromise((resolve, reject) => {
        //             // 当执行回调时，如果有错误进行捕获之后，通过reject抛出去
        //             const fulfilledCallback = () => {
        //                 try {
        //                     const x = onFulfilled(this.result);
        //                     this.resolvePromise(newPromise, x, resolve, reject);
        //                 } catch (e) {
        //                     reject(e);
        //                 }
        //             };

        //             const rejectedCallback = () => {
        //                 try {
        //                     const x = onRejected(this.result);
        //                     this.resolvePromise(newPromise, x, resolve, reject);
        //                 } catch (e) {
        //                     reject(e);
        //                 }
        //             };

        //             if (this.status === 'fulfilled') {
        //                 // 如果状态已经是 fulfilled，则直接执行成功回调，并返回新的 Promise
        //                 setTimeout(fulfilledCallback, 0);
        //             } else if (this.status === 'rejected') {
        //                 // 如果状态已经是 rejected，则直接执行失败回调，并返回新的 Promise
        //                 setTimeout(rejectedCallback, 0);
        //             } else if (this.status === 'pending') {
        //                 // 如果状态仍然是 pending，将回调函数存储起来，等待状态改变后再执行对应的回调
        //                 this.onResolvedCallbacks.push(fulfilledCallback);
        //                 this.onRejectedCallbacks.push(rejectedCallback);
        //             }



        //         })

        //     }

        //     resolvePromise(promise, x, resolve, reject) {
        //         if (promise === x) {
        //             return reject(
        //                 new TypeError('the promise and the return value are the same')
        //             );
        //         }
        //         if (x instanceof MPromise) {
        //             queueMicrotask(() => {
        //                 x.then((y) => {
        //                     this.resolvePromise(promise2, y, resolve, reject);
        //                 }, reject);
        //             });
        //         } else if (typeof x === 'object' || this.isFunction(x)) {
        //             // 如果x是null的时候
        //             if (x === null) {
        //                 return resolve(x);
        //             }
        //             let then = null;
        //             try {
        //                 then = x.then;
        //             } catch (error) {
        //                 return reject(error);
        //             }
        //             if (this.isFunction(then)) {
        //                 let called = false;
        //                 try {
        //                     then.call(
        //                         x,
        //                         (y) => {
        //                             // 使用called作为限制条件，限制只能执行一次
        //                             if (called) {
        //                                 return;
        //                             }
        //                             called = true;
        //                             this.resolvePromise(promise2, y, resolve, reject);
        //                         },
        //                         (r) => {
        //                             if (called) {
        //                                 return;
        //                             }
        //                             called = true;
        //                             reject(r);
        //                         }
        //                     );
        //                 } catch (error) {
        //                     if (called) {
        //                         return;
        //                     } else {
        //                         reject(error);
        //                     }
        //                 }
        //             } else {
        //                 resolve(x);
        //             }
        //         } else {
        //             resolve(x);
        //         }
        //     }


        // }





        const PENGDING = 'pending'
        const FULFILLED = 'fulfilled'
        const REJECTED = 'rejected'
        class MyPromise {
            constructor(executor) {
                try {
                    executor(this.resolve, this.reject)
                } catch (e) {
                    this.reject(e)
                }
            }
            status = PENGDING
            value = undefined
            reason = undefined
            successCallback = []
            failCallback = []
            resolve = value => {
                if (this.status !== PENGDING) return;
                this.status = FULFILLED
                this.value = value
                while (this.successCallback.length > 0) this.successCallback.shift()()
            }
            reject = reason => {
                if (this.status !== PENGDING) return;
                this.status = REJECTED
                this.reason = reason
                while (this.failCallback.length > 0) this.failCallback.shift()()
            }
            then(successCallback, failCallback) {
                successCallback = successCallback ? successCallback : value => value;
                failCallback = failCallback ? failCallback : reason => { throw reason }
                let promise2 = new MyPromise((resolve, reject) => {
                    if (this.status === FULFILLED) {
                        setTimeout(() => {
                            try {
                                let x = successCallback(this.value)
                                resolvePromise(promise2, x, resolve, reject)
                            } catch (e) {
                                reject(e)
                            }
                        }, 0)
                    } else if (this.status === REJECTED) {
                        //   failCallback(this.reason)
                        setTimeout(() => {
                            try {
                                let x = failCallback(this.reason)
                                resolvePromise(promise2, x, resolve, reject)
                            } catch (e) {
                                reject(e)
                            }
                        }, 0)
                    } else {
                        this.successCallback.push(() => {
                            setTimeout(() => {
                                try {
                                    let x = successCallback(this.value)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0)
                        })
                        this.failCallback.push(() => {
                            setTimeout(() => {
                                try {
                                    let x = failCallback(this.reason)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0)
                        })

                    }
                });
                return promise2
            }
            finally(callback) {
                return this.then(value => {
                    // callback()
                    return MyPromise.resolve(callback()).then(() => value)
                    // return value
                }, reason => {
                    return MyPromise.resolve(callback()).then(() => { throw reason })
                    callback()
                    throw reason
                })
            }
            catch(failCallback) {
                return this.then(undefined, failCallback)
            }
            static all(arr) {
                let result = []
                let index = 0
                return new Promise((resolve, reject) => {
                    function addData(key, value) {
                        result[key] = value
                        index++
                        if (index === arr.length) {
                            resolve(result)
                        }
                    }
                    for (let i = 0; i < arr.length; i++) {
                        let current = arr[i];
                        if (current instanceof MyPromise) {
                            current.then(value => addData(i, value), reason => reject(reason))
                        } else {
                            addData(i, arr[i])
                        }
                    }
                })
            }
            static resolve(value) {
                if (value instanceof MyPromise) {
                    return value
                } else {
                    return new Promise(resolve => resolve(value))
                }
            }
        }

        function resolvePromise(promise2, x, resolve, reject) {
            if (promise2 === x) {
                return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
            }
            if (x instanceof MyPromise) {
                x.then(resolve, reject)
            } else {
                resolve(x)
            }
        }





        const a = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                resolve(200)
            }, 1000)
        })
        // console.log(a, 99999999);
        a.then(res => {
            console.log(res, 66666) // 200
            return new MyPromise((resolve, reject) => {
                resolve(500 + res)
            })
        }).then(res => {
            console.log(res, 7777) // 700
        }, (err) => {
            console.log('err----', error);
        })

    </script>
</body>

</html>